# the port from which this bot is getting requests from the internet
#
port: 8080

# the name of the Cisco Spark room handled by this bot
#
room: "Green Power demonstration"

# the token that has been created for this bot should normally be set in
# the environment but you can override the configuration below
#
# CISCO_SPARK_BTTN_BOT: "YWM2OEG4OGItNTQ5YS00MDU2LThkNWEtMJNkODk3ZDZLOGQ0OVGlZWU1NmYtZWyY"

# the email address of the first moderator should normally be set in
# the environment but you can override the configuration below
#
# CISCO_SPARK_BTTN_MAN: "foo.bar@acme.com"

# the sequence of responses given to each button press
#
bt.tn:

  # first press of bt.tn
  #
  - markdown: |
        Green Power has been invoked again
        ==================================

        The [green button](https://d2jaw3pqpetn6l.cloudfront.net/app/uploads/2016/05/27125600/product-images-bttn-normal-green-600x600.jpg) has been pressed, so there is a need for collective action.

        Some context to this event: *Italic*, **bold**, and `monospace`.
        Itemized lists look like this:

          * this one
          * that one
          * the other one

        Unicode is supported. ㋡

    file: files/dashboard.png
    type: "image/png"
    label: "Current status of the server"

    sms:
      - message: "Check Cisco Spark"
      - number: "+352691496401"
      - from: "33644606827"

  # second press of bt.tn
  #
  - markdown: |
        The button has been pressed again, so you may need more information on our processes.
        Reference information can be found here: [Incident Management](https://en.wikipedia.org/wiki/Incident_management_(ITSM))

        Aside from information already shared in this room, you may want to capture more facts and share these with us.
        Please print and fill the form below. Call our Global Service Center at [+44 12 34 56 78](tel:+44-12-34-56-78) for any real-time assistance you may need.

    file: files/IncidentReportForm.pdf
    type: "application/pdf"
    label: "Print and fill this form"

    call:
      - number: "+352691496401"
      - from: "33644606827"
      - url: "http://twimlets.com/holdmusic?Bucket=com.twilio.music.ambient"

  # third press of bt.tn
  #
  - markdown: |
        The button has been pressed again, so there may be a need for immediate collective review of the situation.
        A telephone call is taking place right now. Pre-defined phone numbers will be called directly.

    conference:
      - name: "War Room"
      - number: "+352691496401"
      - from: "33644606827"

  # fourth press of bt.tn
  #
  - file: files/dimension-data.png
    type: "image/png"
    label: "Build new integrated systems and manage them"

  # fifth press of bt.tn
  #
  - file: files/spark.png
    type: "image/png"
    label: "Cisco Spark brings things and human beings together"



