# the port from which this bot is getting requests from the internet
#
port: 8080

# the name of the Cisco Spark room handled by this bot
#
room: "Green Forge"

# the token that has been created for this bot should normally come from
# the environment but you can override the configuration below
#
# CISCO_SPARK_BTTN_BOT: "YWM2OEG4OGItNTQ5YS00MDU2LThkNWEtMJNkODk3ZDZLOGQ0OVGlZWU1NmYtZWyY"

# the address of the first moderator should normally come from
# the environment but you can override the configuration below
#
# CISCO_SPARK_BTTN_MAN: "foo.bar@acme.com"

# the sequence of responses given to each button press
#
bt.tn:

  # first press of bt.tn
  #
  - markdown: |
        Green Power has been invoked again
        ==================================

        The [green button](https://d2jaw3pqpetn6l.cloudfront.net/app/uploads/2016/05/27125600/product-images-bttn-normal-green-600x600.jpg) has been pressed, so there is a need for urgent action.

        Some context to this event: *Italic*, **bold**, and `monospace`.
        Itemized lists look like this:

          * this one
          * that one
          * the other one

        Unicode is supported. ㋡

        And [Incident Management](https://en.wikipedia.org/wiki/Incident_management_(ITSM)) too.

        Call Global Service Center at [+44 12 34 56 78](tel:+44-12-34-56-78) if people are late to join this room. We will continue to provide information so stay tuned.


  # second press of bt.tn
  #
  - file: IncidentReportForm.pdf
    type: "application/pdf"
    label: "Print and fill this report"

  # third press of bt.tn
  #
  - file: bt.tn.png
    type: "image/png"
    label: "European buttons that rock"

  # fourth press of bt.tn
  #
  - file: spark.png
    type: "image/png"
    label: "Cisco Spark brings things and human beings together"

  # fifth press of bt.tn
  #
  - file: dimension-data.png
    type: "image/png"
    label: "Build new integrated systems and manage them"



